application: 'orbital-nuance-814'
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /tasks/delete
  script: cron.application
  login: admin

- url: /.*
  script: views.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest